"""Original, procedurally generated parts: ties, track connectors, footers, bolts.

Nothing here is derived from NoLimits 2 model files. Every shape is built from simple solids
(prisms, lofts, cylinders) using the style's layout constants (gauge, rail radius, spine positions).
A model built with the procedural option contains only geometry generated by this add-on.

Each part uses the same local frame and placement origin as the part it replaces, so build_track /
build_supports can place it the same way. Parts are returned as raw dicts (same layout as the asset pack):
v = vertices, c = face sizes, i = face indices, s = slot per face, slots, bolts / nuts = markers
(pos, normal, size).

Local frames: ties and clamps x = LEFT, y = UP, z = FORWARD. Connectors: plate at y = 0, body along -y.
Footers: top at y = 0.
"""
import numpy as np

MARKER = 0.054  # marker size that places a bolt at scale 1


class Kit:
    def __init__(self, *slots):
        self.slots = list(slots)
        self.V, self.F, self.S = [], [], []
        self.nv = 0
        self.bolts, self.nuts = [], []

    def _slot(self, name):
        if name not in self.slots:
            self.slots.append(name)
        return self.slots.index(name)

    def mesh(self, V, faces, slot):
        V = np.asarray(V, dtype=float).reshape(-1, 3)
        s = self._slot(slot)
        self.V.append(V)
        for f in faces:
            self.F.append([self.nv + int(i) for i in f])
            self.S.append(s)
        self.nv += len(V)
        return self

    def prism(self, poly, c0, c1, slot, axes="xyz"):
        """Extrude a 2D polygon (a, b) from c0 to c1. axes names the world axes of (a, b, c)."""
        poly = np.asarray(poly, dtype=float)
        n = len(poly)
        area = np.sum(poly[:, 0] * np.roll(poly[:, 1], -1) - np.roll(poly[:, 0], -1) * poly[:, 1])
        if area < 0:
            poly = poly[::-1]
        if c1 < c0:
            c0, c1 = c1, c0
        loc = np.vstack([np.c_[poly, np.full(n, c0)], np.c_[poly, np.full(n, c1)]])
        faces = [list(range(n))[::-1], list(range(n, 2 * n))]
        faces += [[i, (i + 1) % n, n + (i + 1) % n, n + i] for i in range(n)]
        perm = ["xyz".index(ch) for ch in axes]
        V = np.zeros_like(loc)
        for k in range(3):
            V[:, perm[k]] = loc[:, k]
        if np.linalg.det(np.eye(3)[perm]) < 0:
            faces = [f[::-1] for f in faces]
        return self.mesh(V, faces, slot)

    def box(self, x0, x1, y0, y1, z0, z1, slot):
        return self.prism([(x0, y0), (x1, y0), (x1, y1), (x0, y1)], z0, z1, slot)

    def bar(self, a, b, h, z0, z1, slot):
        """Flat bar of height h between 2D points a and b (x, y), extruded along z."""
        a, b = np.asarray(a, float), np.asarray(b, float)
        d = b - a
        ln = np.linalg.norm(d)
        if ln < 1e-6:
            return self
        n = np.array([-d[1], d[0]]) / ln * h / 2
        return self.prism([a - n, b - n, b + n, a + n], z0, z1, slot)

    def loft(self, rings, slot, caps=(True, True)):
        """Skin consecutive 3D rings (same point count); faces point away from the loft axis."""
        rings = [np.asarray(r, dtype=float) for r in rings]
        n = len(rings[0])
        r0 = rings[0] - rings[0].mean(0)
        nr = np.sum(np.cross(r0, np.roll(r0, -1, axis=0)), axis=0)
        d = rings[-1].mean(0) - rings[0].mean(0)
        ccw = nr @ d > 0
        V = np.vstack(rings)
        faces = []
        for k in range(len(rings) - 1):
            o = k * n
            for i in range(n):
                j = (i + 1) % n
                q = [o + i, o + j, o + n + j, o + n + i]
                faces.append(q if ccw else q[::-1])
        if caps[0]:
            f = list(range(n))
            faces.append(f[::-1] if ccw else f)
        if caps[1]:
            f = list(range((len(rings) - 1) * n, len(rings) * n))
            faces.append(f if ccw else f[::-1])
        return self.mesh(V, faces, slot)

    def marker(self, pos, nrm, size=MARKER, nut=False):
        (self.nuts if nut else self.bolts).append(list(pos) + list(nrm) + [size])
        return self

    def data(self):
        V = np.vstack(self.V) if self.V else np.zeros((0, 3))
        return dict(v=V.ravel(), c=np.array([len(f) for f in self.F], dtype=np.int64),
                    i=np.array([i for f in self.F for i in f], dtype=np.int64),
                    s=np.array(self.S, dtype=np.int64), slots=list(self.slots or ["steel"]),
                    bolts=np.array(self.bolts, dtype=float).ravel(), nuts=np.array(self.nuts, dtype=float).ravel())


# ------------------------------------------------------------------------------------ ring helpers
def circle2(r, n, rot=0.0):
    t = np.linspace(0, 2 * np.pi, n, endpoint=False) + rot
    return np.c_[r * np.cos(t), r * np.sin(t)]


def rrect2(hx, hz, n=32, k=1.6):
    """Rounded rectangle sampled at n angles (matches circle2 point order, so the two can be lofted)."""
    t = np.linspace(0, 2 * np.pi, n, endpoint=False)
    return np.c_[hx * np.clip(k * np.cos(t), -1, 1), hz * np.clip(k * np.sin(t), -1, 1)]


def rect2(hx, hz):
    return np.array([(-hx, -hz), (hx, -hz), (hx, hz), (-hx, hz)])


def oct2(hx, hz, c):
    return np.array([(hx - c, -hz), (hx, -hz + c), (hx, hz - c), (hx - c, hz),
                     (-hx + c, hz), (-hx, hz - c), (-hx, -hz + c), (-hx + c, -hz)])


def xz_ring(pts, y):
    """2D (x, z) points -> 3D ring at height y."""
    pts = np.asarray(pts, dtype=float)
    return np.c_[pts[:, 0], np.full(len(pts), y), pts[:, 1]]


def yz_ring(pts, x):
    pts = np.asarray(pts, dtype=float)
    return np.c_[np.full(len(pts), x), pts[:, 0], pts[:, 1]]


def xy_ring(pts, z):
    pts = np.asarray(pts, dtype=float)
    return np.c_[pts[:, 0], pts[:, 1], np.full(len(pts), z)]


# ------------------------------------------------------------------------------------------ bolts
def bolts():
    b = Kit("steel")
    b.prism(circle2(0.04, 6, np.pi / 6), 0.0, 0.022, "steel")
    b.prism(circle2(0.017, 12), 0.022, 0.033, "steel")
    b.loft([xy_ring(circle2(0.017, 12), 0.033), xy_ring(circle2(0.012, 12), 0.038)], "steel", (False, True))
    n = Kit("steel")
    n.prism(circle2(0.022, 6, np.pi / 6), 0.003, 0.02, "steel")
    n.prism(circle2(0.011, 12), 0.02, 0.03, "steel")
    return {"proc_bolt": b.data(), "proc_nut": n.data()}


# ---------------------------------------------------------------------------------------- footers
def footers():
    """Concrete blocks, piers and steel base plates. Scaled in plan by the caller (2.8 x column size)."""
    out = {}

    k = Kit("concrete")
    k.loft([xz_ring(rect2(0.6, 0.6), -0.39), xz_ring(rect2(0.6, 0.6), -0.06), xz_ring(rect2(0.55, 0.55), 0.0)],
           "concrete")
    out["old_main"] = k.data()
    out["old_base"] = Kit("concrete").box(-0.52, 0.52, 0.0, 2.4, -0.52, 0.52, "concrete").data()
    out["old_top_box"] = Kit("support").box(-0.47, 0.47, 0.0, 1.0, -0.47, 0.47, "support").data()

    k = Kit("concrete")
    k.loft([xz_ring(rect2(0.75, 0.75), -0.5), xz_ring(rect2(0.75, 0.75), -0.08), xz_ring(rect2(0.7, 0.7), 0.0)],
           "concrete")
    out["steel_main"] = k.data()
    out["steel_base"] = Kit("concrete").box(-0.66, 0.66, 0.0, 2.0, -0.66, 0.66, "concrete").data()
    out["steel_top"] = Kit("support").box(-0.45, 0.45, 0.0, 1.0, -0.45, 0.45, "support").data()

    # gusset fins: profile in (radial z, height y), thickness along x (scaled to 2.5 cm by the caller)
    for name, zin, zout in (("tri_fin", -0.25, 1.0), ("tri_fin_arrow", -0.61, 1.2)):
        prof = [(zin, 0.0), (zout, 0.0), (zout, 0.07), (0.0, 1.0), (zin, 1.0)]
        out[name] = Kit("support").prism(prof, -0.5, 0.5, "support", axes="zyx").data()

    for name, sq in (("round", False), ("square", True)):
        ring = (lambda r: rect2(r, r)) if sq else (lambda r: circle2(r, 24))
        k = Kit("concrete")
        k.loft([xz_ring(ring(0.75), -0.41), xz_ring(ring(0.75), -0.05), xz_ring(ring(0.7), 0.0)], "concrete")
        out["wood_%s_main" % name] = k.data()
        k = Kit("concrete")
        k.loft([xz_ring(ring(0.66), 0.0), xz_ring(ring(0.66), 2.0)], "concrete")
        out["wood_%s_base" % name] = k.data()

    # post mount: steel angle, one leg against the post (x = 0), one on the pier
    k = Kit("metal")
    k.box(0.0, 0.012, 0.0, 0.15, -0.14, 0.14, "metal")
    k.box(0.0, 0.08, 0.0, 0.012, -0.14, 0.14, "metal")
    k.marker((0.012, 0.1, 0.07), (1, 0, 0), 0.03).marker((0.012, 0.1, -0.07), (1, 0, 0), 0.03)
    out["wood_mount"] = k.data()
    return out


# ------------------------------------------------------------------------------------- connectors
def plate(hx, hz, y0, y1, slot, bolt_inset=0.08):
    k = Kit(slot)
    k.prism(oct2(hx, hz, min(hx, hz) * 0.25), y0, y1, slot, axes="xzy")
    for sx in (-1, 1):
        for sz in (-1, 1):
            p = (sx * (hx - bolt_inset), y1, sz * (hz - bolt_inset))
            k.marker(p, (0, 1, 0))
            k.marker((p[0], y0, p[2]), (0, -1, 0), nut=True)
    return k.data()


# (half width x, half length z, depth) of the column-head connectors by nominal column size (inches)
BM_SIZES = {20: (0.37, 0.305, 0.792), 30: (0.408, 0.427, 1.189), 42: (0.423, 0.597, 1.664)}


def column_head(hx, hz, depth, D, horizontal):
    """Box-spine column head. Spine-coloured plate at y = 0 (the caller lofts it into the spine).
    vertical: tapered neck down to a bolted flange that sits on a round column of diameter D.
    horizontal: web down to a collar around a horizontal cross beam (beam axis = x)."""
    k = Kit("support", "spine")
    t = 0.03
    k.prism(oct2(hx, hz, 0.04), -t, 0.0, "spine", axes="xzy")
    for sx in (-1, 1):
        for sz in (-1, 1):
            k.marker((sx * (hx - 0.06), -t, sz * (hz - 0.06)), (0, -1, 0), nut=True)
    n = 32
    if not horizontal:
        rc, rf, ft = D / 2 + 0.02, D / 2 + 0.09, 0.07
        k.loft([xz_ring(rrect2(hx * 0.8, hz * 0.8, n), -t), xz_ring(circle2(rc, n), -depth + ft),
                xz_ring(circle2(rf, n), -depth + ft), xz_ring(circle2(rf, n), -depth)], "support")
        nb = 8 if D < 0.6 else (10 if D < 0.9 else 12)
        rb = D / 2 + 0.055
        for p in circle2(rb, nb, np.pi / nb):
            k.marker((p[0], -depth + ft, p[1]), (0, 1, 0))
            k.marker((p[0], -depth, p[1]), (0, -1, 0), nut=True)
    else:
        R = D / 2 + 0.03
        yc = -depth + R
        k.loft([xz_ring(rrect2(hx * 0.8, hz * 0.8, n), -t), xz_ring(rrect2(hx * 0.8, R * 0.45, n), yc + R * 0.6)],
               "spine")
        k.loft([yz_ring(circle2(R, n), -hx * 0.75) + [0, yc, 0], yz_ring(circle2(R, n), hx * 0.75) + [0, yc, 0]],
               "support")
        for sx in (-1, 1):
            for sz in (-1, 1):
                k.marker((sx * hx * 0.5, yc + sz * 0.0, sz * R), (0, 0, sz), 0.04)
    return k.data()


def clamp(style, option, gauge, rail_r, attach):
    """Track clamp placed like a tie: saddles under the rails, a truss down (or up) to a pad at the
    support attach point."""
    k = Kit("tie", "support")
    g2 = gauge / 2
    r = max(rail_r, 0.03)
    w = 0.06
    h = max(0.05, r * 0.8)
    if g2 <= 0:
        k.box(-0.15, 0.15, attach - 0.02, attach + 0.02, -w, w, "support")
        return k.data()
    below = attach < 0
    ys = -r * 0.9 if below else r * 0.9
    for x in (-g2, g2):
        k.prism(_chair(x, r, below), -w, w, "tie")
        k.bar((x, ys), (0, attach), h, -w * 0.8, w * 0.8, "tie")
    k.bar((-g2, ys), (g2, ys), h, -w * 0.8, w * 0.8, "tie")
    for p in option["parts"]:
        if p[0] == "tube":
            _, x, y, tr = p
            _collar(k, x, y, tr, w * 1.1, "tie")
    pad = 0.035 if below else -0.035
    k.box(-0.16, 0.16, min(attach, attach + pad), max(attach, attach + pad), -w * 1.4, w * 1.4, "support")
    return k.data()


def _chair(x, r, below=True):
    """Saddle block under (or over) a rail at x: overlaps the rail's lower half so they fuse."""
    s = -1 if below else 1
    return [(x - r * 1.15, s * (r + 0.03)), (x + r * 1.15, s * (r + 0.03)), (x + r * 0.75, 0.0), (x - r * 0.75, 0.0)]


def _collar(k, x, y, tr, hw, slot, n=20):
    """Band clamp around a tube at (x, y) running along z: annulus from -hw to hw."""
    ro, ri = tr + 0.025, tr * 0.97
    ang = np.linspace(0, 2 * np.pi, n, endpoint=False)
    c, s = np.cos(ang), np.sin(ang)
    V = np.vstack([np.c_[x + r * c, y + r * s, np.full(n, z)] for z in (-hw, hw) for r in (ro, ri)])
    i = np.arange(n)
    j = (i + 1) % n
    o0, n0, o1, n1 = 0, n, 2 * n, 3 * n
    quads = np.concatenate([np.c_[o0 + i, o0 + j, o1 + j, o1 + i], np.c_[n0 + j, n0 + i, n1 + i, n1 + j],
                            np.c_[o1 + i, o1 + j, n1 + j, n1 + i], np.c_[o0 + j, o0 + i, n0 + i, n0 + j]])
    k.mesh(V, quads.tolist(), slot)


def rmc_shoe(x0, x1, yb):
    """Steel shoe under one I-box rail (bottom at yb): saddle plate, web, base plate on the cap channel."""
    k = Kit("tie", "metal")
    xc = (x0 + x1) / 2
    k.box(x0 - 0.025, x1 + 0.025, yb - 0.022, yb + 0.006, -0.12, 0.12, "tie")
    k.box(xc - 0.013, xc + 0.013, yb - 0.125, yb - 0.02, -0.1, 0.1, "metal")
    k.box(xc - 0.03, xc + 0.03, yb - 0.125, yb - 0.02, -0.013, 0.013, "metal")
    k.box(x0 - 0.035, x1 + 0.035, yb - 0.143, yb - 0.123, -0.124, 0.124, "metal")
    for sx in (-1, 1):
        for sz in (-1, 1):
            k.marker((xc + sx * (x1 - x0) * 0.4, yb - 0.123, sz * 0.09), (0, 1, 0), 0.04)
    return k.data()


# ------------------------------------------------------------------------------------------- ties
def tie(style, option, gauge, rail_r):
    """Cross-tie for any style, built from the style's rails and spine parts."""
    k = Kit("tie")
    parts = option["parts"]
    boxes = [p for p in parts if p[0] == "box"]
    tubes = [p for p in parts if p[0] == "tube"]
    g2 = gauge / 2
    if style.get("wooden") or (rail_r <= 0 and len(boxes) == 2):
        # track on two rail stacks (wood / I-box / railroad): a tie under both stacks
        X = max(max(abs(p[1]), abs(p[2])) for p in boxes)
        yb = min(p[3] for p in boxes)
        if style.get("rasc") == "rmc":
            k.box(-X - 0.03, X + 0.03, yb - 0.03, yb + 0.004, -0.04, 0.04, "tie")
            for p in boxes:
                k.box(p[1] - 0.012, p[1] + 0.001, yb, yb + 0.06, -0.035, 0.035, "tie")
                k.box(p[2] - 0.001, p[2] + 0.012, yb, yb + 0.06, -0.035, 0.035, "tie")
        elif style.get("wooden"):
            ya = option.get("attach") or yb - 0.13
            k.box(-X - 0.05, X + 0.05, ya, yb + 0.002, -0.075, 0.075, "tie")
        else:
            k.box(-X - 0.35, X + 0.35, yb - 0.2, yb + 0.002, -0.11, 0.11, "tie")
        return k.data()
    if g2 <= 0 or rail_r <= 0:
        return k.data()  # e.g. monorail: no ties

    r = rail_r
    w = 0.055 if r < 0.075 else 0.07
    h = max(0.045, r * 0.65)
    rails = [(-g2, 0.0, r), (g2, 0.0, r)] + [(p[1], p[2], p[3]) for p in style.get("extra", [])]
    X = max(abs(x) for x, _, _ in rails)
    y_hi = -r * 0.5
    y_lo = y_hi - h
    ym = (y_hi + y_lo) / 2
    k.box(-X, X, y_lo, y_hi, -w / 2, w / 2, "tie")
    for x, y, rr in rails:
        k.prism(_chair(x, rr), -w * 0.65, w * 0.65, "tie")

    small = []
    for _, x, y, tr in tubes:
        if tr >= 0.12:
            # big spine: tapered web plate from the cross bar into the spine, plus a band clamp
            a = min(X * 0.8, tr * 1.8 + 0.12)
            yt = y + tr * 0.6 if y < 0 else y - tr * 0.6
            ya = y_lo + 0.01 if y < 0 else y_hi - 0.01
            k.prism([(x - a, ya), (x + a, ya), (x + tr * 0.75, yt), (x - tr * 0.75, yt)], -w * 0.3, w * 0.3, "tie")
            _collar(k, x, y, tr, w * 0.6, "tie")
        else:
            small.append((x, y, tr))
            _collar(k, x, y, tr, w * 0.6, "tie")
    for x, y, tr in small:
        yt = y + tr * 0.5 if y < 0 else y - tr * 0.5
        for rx in (-g2, g2):
            # one lower tube: V truss from both rails; several: each rail feeds the tubes on its side
            if len(small) == 1 or abs(x) < 1e-3 or np.sign(rx) == np.sign(x):
                k.bar((rx, ym), (x, yt), h * 0.8, -w * 0.3, w * 0.3, "tie")
    if len(small) >= 2:
        s = sorted(small)
        for (xa, ya_, _), (xb, yb_, _) in zip(s, s[1:]):
            k.bar((xa, ya_), (xb, yb_), h * 0.8, -w * 0.3, w * 0.3, "tie")

    if boxes:
        # box spine: web plate from the cross bar down onto the top of the highest box
        top = max(boxes, key=lambda p: p[4])
        _, x0, x1, y0, y1 = top
        if y1 < y_lo - 0.01:
            a = min(X * 0.85, max(abs(x0), abs(x1)) + 0.25)
            k.prism([(x0, y1 - 0.02), (x1, y1 - 0.02), (a, y_lo + 0.01), (-a, y_lo + 0.01)], -w * 0.3, w * 0.3,
                    "tie")
            # side straps hugging the box
            d = min(0.2, (y1 - y0) * 0.35)
            for xs, xe in ((x0 - 0.012, x0 + 0.001), (x1 - 0.001, x1 + 0.012)):
                k.box(xs, xe, y1 - d, y1 + 0.001, -w * 0.4, w * 0.4, "tie")
    return k.data()


# ------------------------------------------------------------------------------------------- pack
def pack(style, option, gauge, rail_r, attach):
    """Every part build_track / build_supports can ask for, as raw dicts keyed like the asset pack.
    Ties are left empty: build_track falls back to core.generated_tie (procedural.tie)."""
    r = {
        "corkcon0": plate(0.4, 0.4, -0.012, 0.012, "support"),
        "bmcon0": plate(0.45, 0.45, -0.02, 0.0, "spine"),
        "4dcon_single": plate(0.4, 0.4, -0.03, 0.03, "support"),
        "4dcon_double": plate(0.8, 0.4, -0.03, 0.03, "support"),
    }
    for n, (hx, hz, depth) in BM_SIZES.items():
        D = n * 0.0254
        for kind, horiz in (("vert", False), ("horz", True)):
            r["bmcon_%s_%d" % (kind, n)] = column_head(hx, hz, depth, D, horiz)
            r["bmcon_dive_%s_%d" % (kind, n)] = column_head(hx + 0.17, hz, depth, D, horiz)
    cl = clamp(style, option, gauge, rail_r, attach)
    for name in ("int_900_2t", "int_900_3t", "int_900_4t", "gerst_1200_2t", "gerst_1200_3t", "schwarz_900_2t",
                 "suspended_horz"):
        r[name] = cl
    boxes = [p for p in option["parts"] if p[0] == "box"]
    for p in boxes:
        side = "left" if (p[1] + p[2]) > 0 else "right"
        r["ironhorse_rasc1_%s" % side] = rmc_shoe(p[1], p[2], p[3])
    b = bolts()
    return {"ties": {}, "rascs": r, "footers": footers(), "bolts": {"bolt": b["proc_bolt"], "nut": b["proc_nut"]}}
